### ISSUE TITLE
Api requests do not execute after active record used

### ISSUE THREAD

**Issue by valenso** [Patreon/patreon-ruby#13]
I catch an error that I can't solve. Why Your api call does not works after active record call?

```
require 'patreon'
require File.expand_path('../../config/environment',  __FILE__)
@api_client = Patreon::API.new("key")


def check_and_create(message, bot)
  if !User.exists?(telegram_id: 1)
    User.create(:telegram_id => 1, :first_name => "message.from.first_name")
    return User.last
  else
    return User.where(telegram_id: 1).first
  end
end

#block works
patron_response = @api_client.fetch_campaign_and_patrons()
p patron_response.data[0].pledges[2].patron.email
p patron_response.data[0].pledges[2].reward.id

user = check_and_create(nil, nil)

#block does not work
patron_response = @api_client.fetch_campaign_and_patrons()
p patron_response.data[0].pledges[2].patron.email
p patron_response.data[0].pledges[2].reward.id
```

The error looks like:

```
/Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:152:in `set_key': undefined method `campaign=' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:94:in `block (2 levels) in build'
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:80:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:80:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:76:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:76:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/json-api-vanilla-1.0.1/lib/json-api-vanilla/parser.rb:20:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/patreon-0.5.0/lib/patreon/api.rb:53:in `parse_json'
	from /Library/Ruby/Gems/2.3.0/gems/patreon-0.5.0/lib/patreon/api.rb:33:in `get_parse_json'
	from /Library/Ruby/Gems/2.3.0/gems/patreon-0.5.0/lib/patreon/api.rb:12:in `fetch_campaign'
	from /Library/Ruby/Gems/2.3.0/gems/patreon-0.5.0/lib/patreon/api.rb:18:in `fetch_campaign_and_patrons'
	from bin/untitled.rb:21:in `<main>'
```

**Comment by valenso** [comment]
I catch a name conflict.
Just rename my model User to Botuser and it helps to solve the issue

**Comment by spencerhandley** [comment]
Thanks for pointing this out @valenso
